### ISSUE TITLE
Make Docker Image

### ISSUE THREAD

**Issue by avalonche** [flashbots/mev-flood#26]
We want to include this as part of the EF tooling to test the whole relay and builder infrastructure. In order to do that we'll need to provide them a docker image like https://github.com/MariusVanDerWijden/tx-fuzz so they can build and send test bundles.

**Comment by metachris** [comment]
great call sarah 🙏 

should be relatively simple to push this into a docker repository. i can create one and will add sarah as team Docker member.

can we please try a "relatively" small base image, like `node:20.2-alpine` which is at least only 50MB instead of 300?

- https://hub.docker.com/_/node/tags
- https://hub.docker.com/layers/library/node/20.2-alpine/images/sha256-f25b0e9d3d116e267d4ff69a3a99c0f4cf6ae94eadd87f1bf7bd68ea3ff0bef7?context=explore

See also mev-boost for a reference on how to do Docker image builds in Makefile and Github CI:

- https://github.com/flashbots/mev-boost/blob/develop/Makefile#L75-L79
- https://github.com/flashbots/mev-boost/blob/develop/.github/workflows/release.yaml#L12-L59

**Comment by metachris** [comment]
@zeroXbrock could you use node-alpine as base image? https://github.com/flashbots/mev-flood/blob/main/Dockerfile#L2

That's only be 50 MB instead of 300

**Comment by avalonche** [comment]
Completed as part of https://github.com/flashbots/mev-flood/pull/35
